branch: mastrer
checksum: 1235b008a49d08307176f1ca8966cdd3ac92d1da026967e09f9df218b647f6b2
default: true
language: python3
max_per_day: 3
python:
  importable: true
  scriptify: true
testset: wk1
version: 3
