branch: master
checksum: b6755a8c7270715645b6bd7b164e7964aab57b6b0260f2a240e238418fcda407
default: true
language: python3
max_per_day: 3
python:
  importable: true
  scriptify: true
testset: wk1
version: 3
